- platform: cryptoinfo
  cryptocurrency_name: "bitcoin"
  currency_name: "usd"

- platform: cryptoinfo
  cryptocurrency_name: "ethereum"
  currency_name: "usd"

- platform: cryptoinfo
  cryptocurrency_name: "celsius-degree-token"
  currency_name: "usd"

- platform: cryptoinfo
  cryptocurrency_name: "ripple"
  currency_name: "usd"

- platform: cryptoinfo
  cryptocurrency_name: "polkadot"
  currency_name: "usd"

- platform: cryptoinfo
  cryptocurrency_name: "yearn-finance"
  currency_name: "usd"

- platform: cryptoinfo
  cryptocurrency_name: "matic-network"
  currency_name: "usd"

