- platform: alpha_vantage
  api_key: !secret alpha_vantage_api_key
  symbols:
  - symbol: AMD
    name: Advanced Micro Devices
  - symbol: GOOGL
    name: Google
  - symbol: AMZN
    name: Amazon
  - symbol: APPL
    name: Apple
  - symbol: APPL
    name: Apple
  - symbol: BKNG
    name: Booking.com
  - symbol: BEP
    name: Brookfield Renewable Partners
  - symbol: KO
    name: Coca-Cola
  - symbol: EZJ
    name: easyJet
  - symbol: FB
    name: Facebook
  - symbol: FIT
    name: Fitbit
  - symbol: INTC
    name: Intel
  - symbol: ECAR
    name: iShares Electric Vehicles 
  - symbol: INRG
    name: iShares Global Clean Energy 
  - symbol: ITM
    name: ITM Power
  - symbol: MSFT
    name: Microsoft
  - symbol: NTLX
    name: Netflix
  - symbol: NVDA
    name: Nvidia
  - symbol: QCOM
    name: Qualcomm
  - symbol: TSLA
    name: Tesla
  - symbol: W
    name: Wayfair
  - symbol: ZM
    name: Zoom

  foreign_exchange:
  - name: GBP_USD
    from: GBP
    to: USD
  - name: GBP_INR
    from: GBP
    to: INR
  - name: BTC_GBP
    from: BTC
    to: GBP
  - name: ETH_GBP
    from: ETH
    to: GBP
