version: '3'
services:
  #======================= Home Assistant =====================#
  # Hosts home-assistant instance
  #============================================================#
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./home-assistant/config/:/config
    ports:
      - "8123:8123"
    depends_on:
      - database
    links:
      - database


  #========================== Database ========================#
  # MariaDB database for home assistant
  #============================================================#
  database:
    container_name: database
    image: mariadb/server:latest
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./database/data/:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - database/.env


  #====================== Zigbee dongle =======================#
  # Runs deconz to support conbee ii usb zigbee dongle
  #============================================================#
  zigbee-app:
    container_name: zigbee-app
    image: marthoc/deconz:latest
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
      - "5900:5900"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zigbee-app/config:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM0
    env_file:
      - zigbee-app/.env


  #=========================== MQTT ===========================#
  # Runs a mosquitto mqtt broker
  #============================================================#
  mqtt-broker:
    container_name: mqtt-broker
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mqtt-broker/:/mosquitto/


  #====================== Media server ========================#
  # Runs Plex media server in docker. TODO: Setup to use 
  # graphic card for hardware accelarated transcoding.
  #============================================================#
  media-server:
    container_name: media-server
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./media-server/config:/config
      - ./media-server/transcode:/transcode
      - ./media-server/data:/data/internal-hd
      - /media/external-hd:/data/external-hd
    env_file:
      - media-server/.env
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    labels:
      ofelia.enabled: "true"

      # Cleanup empty dirs left after move - every Sunday at 5 am
      # Cannot run this on local-sync container due to find tool not supporting -empty option
      ofelia.job-exec.cleanup-local-data-move.schedule: "0 0 5 * * 0"
      ofelia.job-exec.cleanup-local-data-move.command: "find /data/internal-hd -mindepth 2 -type d -empty -delete"

  #======================== Local sync =========================#
  # Local sync moves data from Internal to External HD. Has a 
  # cron task setup using the cron-service to do this periodically.
  #=============================================================#
  local-sync:
    container_name: local-sync
    image: eeacms/rsync:latest
    restart: unless-stopped
    command: tail -F keep-alive
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./media-server/data:/data/internal-hd
      - /media/external-hd:/data/external-hd
    labels:
      ofelia.enabled: "true"

      # Move data from internal to external HD - every Sunday at 3 am
      ofelia.job-exec.local-data-move.schedule: "0 0 3 * * 0" 
      ofelia.job-exec.local-data-move.command: "rsync -arvP --remove-source-files --exclude='downloads' /data/internal-hd/ /data/external-hd/"


  #====================== Monitoring ========================#
  # Runs Glances to monitor the resources of the Host
  #============================================================#
  monitoring:
    container_name: monitoring
    image: nicolargo/glances:latest
    restart: unless-stopped
    ports:
      - "61208-61209:61208-61209"
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /media/external-hd:/external-hd:ro
    environment:
      - "GLANCES_OPT=-w"


  #======================== Cron service ======================#
  # Schedules cron jobs on different docker containers or host
  #============================================================#
  cron-service:
    container_name: cron-service
    image: mcuadros/ofelia:latest
    restart: always
    command: daemon --docker
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro


  #=================== Backup & cloud sync ====================#
  # Creates backups and syncs them to a cloud service
  #============================================================#
  cloud-backup:
    container_name: cloud-backup
    image: rclone/rclone:latest
    restart: always
    command: rcd --rc-web-gui --rc-addr :5572
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./cloud-backup/config:/config/rclone
      - ./cloud-backup/script:/script
      - ./cloud-backup/backups:/backups
      - ./:/all-containers-data:ro
    labels:
      ofelia.enabled: "true"

      # Create an archive at 2 am every day
      ofelia.job-exec.archive-docker-volume.schedule: "0 0 2 * * *" 
      ofelia.job-exec.archive-docker-volume.command: "/bin/sh -c /script/backup.sh"

      # Sync to cloud service at 3 am every day
      ofelia.job-exec.cloud-sync.schedule: "0 0 3 * * *" 
      ofelia.job-exec.cloud-sync.command: "rclone -vv sync /backups cloud:/Home-Assistance-Backups"


  #===================== Torrent client =======================#
  # Runs tranmission torrent client through an OpenVPN tunnel
  #============================================================#
  torrent-client:
    container_name: torrent-client
    image: haugene/transmission-openvpn:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./torrent-client/data:/data
      - ./media-server/data:/internal-hd
    devices:
      - /dev/net/tun
    env_file:
      - torrent-client/.env
    network_mode: host

