version: '3'
services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - ./docker-volume/home-assistant/:/config
    env_file: 
      - ./docker-env/common.env
    restart: always
    network_mode: host

  # Schedules cron jobs on docker containers or host as per config
  # cron-service:
  #   container_name: cron-service
  #   image: mcuadros/ofelia:latest
  #   command: daemon --docker
  #   volumes:
  #     # required to schedule cron jobs on other containers
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   labels:
  #     ofelia.enabled: "true"
  #     ofelia.job-exec.datecron.schedule: "@every 5s"
  #     ofelia.job-exec.datecron.command: "uname -a"

  # Manages syncing selected data to a cloud service
  rclone-service:
    container_name: rclone
    image: rclone/rclone:latest
    command: rcd --rc-web-gui --rc-addr :5572
    restart: always
    volumes:
      - ./docker-volume/rclone-service/config/:/config/rclone
      - ./docker-volume/rclone-service/data/:/data
    env_file: 
      - ./docker-env/common.env
