version: '3'
services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - ./docker-volume/home-assistant/:/config
    env_file: 
      - ./docker-env/common.env
    restart: always
    network_mode: host

  # Schedules cron jobs on docker containers or host
  ofelia:
    container_name: ofelia
    build: https://github.com/mcuadros/ofelia.git
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file: 
      - ./docker-env/common.env

  # Manages syncing selected data to a cloud service and creating archives
  rclone:
    container_name: rclone
    image: rclone/rclone:latest
    command: rcd --rc-web-gui --rc-addr :5572
    restart: always
    volumes:
      - ./docker-volume/rclone/config/:/config/rclone
      - ./docker-volume/rclone/data/:/data
      - ./docker-volume:/docker-volume
    env_file: 
      - ./docker-env/common.env
      - ./docker-env/rclone.env
    labels:
      ofelia.enabled: "true"

      # Create an archive at 2 am every day
      ofelia.job-exec.archive-docker-volume.schedule: "0 0 2 * * *" 
      ofelia.job-exec.archive-docker-volume.command: "/bin/sh -c /docker-volume/rclone/script/backup.sh"

      # Sync to cloud service at 3 am every day
      ofelia.job-exec.cloud-sync.schedule: "0 0 3 * * *" 
      ofelia.job-exec.cloud-sync.command: "${CLOUD_SYNC_COMMAND}"
