version: '3'
services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - ./docker-volume/home-assistant/:/config
    env_file: 
      - ./docker-env/common.env
    restart: always
    network_mode: host

  # Schedules cron jobs on docker containers or host
  ofelia:
    container_name: ofelia
    build: https://github.com/mcuadros/ofelia.git
    depends_on:
      - rclone
      - home-assistant
    command: daemon --docker
    volumes:
      - ./docker-volume:/docker-volume
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file: 
      - ./docker-env/common.env
    labels:
      # Create an archive at 2 am every day
      ofelia.job-local.archive-docker-volume.schedule: "0 0 2 * * *" 
      ofelia.job-local.archive-docker-volume.command: "docker-volume/ofelia/backup.sh"

  # Manages syncing selected data to a cloud service
  rclone:
    container_name: rclone
    image: rclone/rclone:latest
    command: rcd --rc-web-gui --rc-addr :5572
    restart: always
    volumes:
      - ./docker-volume/rclone/config/:/config/rclone
      - ./docker-volume/rclone/data/:/data
    env_file: 
      - ./docker-env/common.env
    labels:
      ofelia.enabled: "true"
      # Sync to dropbox at 3 am every day
      ofelia.job-exec.dropbox-sync.schedule: "0 0 3 * * *" 
      ofelia.job-exec.dropbox-sync.command: "rclone sync /data dropbox:/"
