version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - ./config/:/config
    env_file: 
      - ./docker-env/common.env
    restart: always
    network_mode: host
