version: '3'
services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - ./docker-volume/home-assistant/:/config
    env_file: 
      - ./docker-env/common.env
    restart: always
    network_mode: host

  # Schedules cron jobs on docker containers or host
  ofelia:
    container_name: ofelia
    image: mcuadros/ofelia:latest
    depends_on:
      - rclone
      - home-assistant
    command: daemon --config=/config/config.ini
    volumes:
      # required to schedule cron jobs on other containers
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker-volume/ofelia/:/config/
    env_file: 
      - ./docker-env/common.env

  # Manages syncing selected data to a cloud service
  rclone:
    container_name: rclone
    image: rclone/rclone:latest
    command: rcd --rc-web-gui --rc-addr :5572
    restart: always
    volumes:
      - ./docker-volume/rclone/config/:/config/rclone
      - ./docker-volume/rclone/data/:/data
    env_file: 
      - ./docker-env/common.env
