#=================================================
# Contextual lights:
# Scripts to turn lights on smoothly using different
# intial behaviours based on context (such as time)
#=================================================

##################   Turn on smart   ##################
lights_on_smart:
  alias: Lights on with smart transition
  icon: mdi:lightbulb-on
  mode: queued
  fields:
    light:
      description: 'Entity id of the light to interact on'
      example: light.corridor_lights
  sequence:
  - service: light.turn_on
    data_template:
      entity_id: "{{ light }}"
      brightness: "{{ states('input_number.contextual_brightness') | int }}"
      rgb_color: [255, 255, 255]
  - service: light.turn_on
    data_template:
      entity_id: "{{ light }}"
      brightness: 255
      transition: 10
