#### Philips Hue dimmer switch with deconz ####
# X000 Initial Press
# X001 Hold
# X002 Release (after press)
# X003 Release (after hold)
# X - can be 1 to 3 
hue_dimmer_switch:
  alias: Hue dimmer switch
  icon: mdi:light-switch
  mode: parallel
  fields:
    event:
      description: 'The event number as sent by deconz (between 1000 and 4003)'
      example: 1000
    light:
      description: 'Entity id of the light to interact on'
      example: light.corridor_lights
  sequence:
  - service_template: >
      {% if event | int >= 1000 and event | int <= 1003 %}
        script.hue_dimmer_switch_on_button
      {%-elif event | int >= 2000 and event | int <= 2003 %}
        script.hue_dimmer_switch_up_button
      {%-elif event | int >= 3000 and event | int <= 3003 %}
        script.hue_dimmer_switch_down_button
      {%-elif event | int >= 4000 and event | int <= 4003 %}
        script.hue_dimmer_switch_off_button
      {% endif %}
    data_template:
      event: "{{ event }}"
      light: "{{ light }}"

#### ON #####
hue_dimmer_switch_on_button:
  alias: Hue dimmer switch "On" button
  icon: mdi:power-on
  mode: parallel
  fields:
    event:
      description: 'The event number as sent by deconz (between 1000 and 1003)'
      example: 1000
    light:
      description: 'Entity id of the light to turn on'
      example: light.corridor_lights
  sequence:
  - condition: template
    value_template: '{{ event | int == 1000 or event | int == 1001 }}'
  - service: light.turn_on
    data_template:
      entity_id: "{{ light }}"
      brightness: >-
        {% if event | int == 1000 %}
          100
        {%-elif event | int == 1001 %}
          255
        {% endif %}

#### INCREASE #####
hue_dimmer_switch_up_button:
  alias: Hue dimmer switch "Up" button
  icon: mdi:brightness-5
  mode: parallel
  fields:
    event:
      description: 'The event number as sent by deconz (between 2000 and 2003)'
      example: 2000
    light:
      description: 'Entity id of the light to turn off'
      example: light.corridor_lights
  sequence:
  - condition: template
    value_template: '{{ event | int == 2000 or event | int == 2001 }}'
  - service: light.turn_on
    data_template:
      entity_id: "{{ light }}"
      brightness_step: >-
        {% if event | int == 2000 %}
          40
        {%-elif event | int == 2001 %}
          80
        {% endif %}

#### DECREASE #####
hue_dimmer_switch_down_button:
  alias: Hue dimmer switch "Down" button
  icon: mdi:brightness-2
  mode: parallel
  fields:
    event:
      description: 'The event number as sent by deconz (between 3000 and 3003)'
      example: 3000
    light:
      description: 'Entity id of the light to turn off'
      example: light.corridor_lights
  sequence:
  - condition: template
    value_template: '{{ event | int == 3000 or event | int == 3001 }}'
  - service: light.turn_on
    data_template:
      entity_id: "{{ light }}"
      brightness_step: >-
        {% if event | int == 3000 %}
          -40
        {%-elif event | int == 3001 %}
          -80
        {% endif %}

#### OFF #####
hue_dimmer_switch_off_button:
  alias: Hue dimmer switch "Off" button
  icon: mdi:power-off
  mode: parallel
  fields:
    event:
      description: 'The event number as sent by deconz (between 4000 and 4003)'
      example: 4000
    light:
      description: 'Entity id of the light to turn off'
      example: light.corridor_lights
  sequence:
  - service: light.turn_off
    data_template:
      entity_id: "{{ light }}"
