title: Sensor Monitor
icon: mdi:eye
path: sensor-monitor
panel: true

cards:
- type: custom:layout-card
  layout: horizontal
  cards:
  - !include /config/lovelace/tiles/tile_room_temperatures.yaml
  - !include /config/lovelace/tiles/tile_room_humidities.yaml
  - !include /config/lovelace/tiles/tile_sensor_batteries.yaml
