title: Server Monitoring
icon: mdi:server
path: server-monitoring
panel: true

cards:
- type: custom:layout-card
  cards:
  - !include /config/lovelace/tiles/tile_home_lab.yaml
  - !include /config/lovelace/tiles/tile_plant_monitor_1.yaml
  - !include /config/lovelace/tiles/tile_plant_monitor_2.yaml
  - !include /config/lovelace/tiles/tile_torrent_client.yaml
