title: Home
icon: mdi:home-heart
path: home

badges:
- entity: sun.sun

- entity: person.praveen
- entity: person.mar

- entity: sensor.living_room_environment
  name: Living room
- entity: sensor.bedroom_environment
  name: Bedroom
- entity: sensor.hallway_environment
  name: Hallway
- entity: sensor.guestroom_environment
  name: Guest room

cards:
- type: glance
  title: Smart lighting
  entities:
  - entity: input_boolean.contextual_lights
    name: Time based
    tap_action:
      action: toggle
    hold_action:
      action: more-info
  - entity: input_boolean.motion_lighting
    name: Motion sense
    tap_action:
      action: toggle
    hold_action:
      action: more-info

- !include /config/lovelace/tiles/tile_all_lights.yaml
- !include /config/lovelace/tiles/tile_all_curtains.yaml
- !include /config/lovelace/tiles/tile_all_media_players.yaml
- !include /config/lovelace/tiles/tile_robovac.yaml
