title: Server Monitoring
icon: mdi:server
path: server-monitoring
panel: true

cards:
- type: custom:layout-card
  layout: horizontal
  cards:
  - !include /config/lovelace/tiles/tile_home_lab.yaml
  - !include /config/lovelace/tiles/tile_plant_monitor_indoor.yaml
  - !include /config/lovelace/tiles/tile_plant_monitor_outdoor.yaml
  - !include /config/lovelace/tiles/tile_torrent_client.yaml
