title: Plants Monitoring
icon: mdi:leaf
path: plant-monitoring
cards:
- type: 'custom:vertical-stack-in-card'
  cards:
  - type: entities
    entities:
    - entity: sensor.plants_total
      name: Total
    - entity: sensor.plants_problem
      name: Needs attention
    - entity: sensor.plants_water_low
      name: Needs water
    - entity: sensor.plants_fertilizer_low
      name: Needs fertilizer
    - entity: sensor.plants_battery_low
      name: Needs battery change

  - type: glance
    entities:
    - entity: input_boolean.plant_water_notifications
      name: Water notifications
      tap_action:
        action: toggle
      hold_action:
        action: more-info
    - entity: input_boolean.plant_fertilize_notifications
      name: Fertilize notifications
      tap_action:
        action: toggle
      hold_action:
        action: more-info

- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.sago_palm

- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.spineless_yucca

- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.rubber_plant

- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.swiss_cheese

- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.cat_palm

- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.spider_plant

- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.dumbcane

- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.dragon_tree

- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.chilli_plant

- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.cherry_tomato

- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.dining_left

- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.dining_middle

- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.dining_right

- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.graptoveria

