title: Plants Monitoring
icon: mdi:leaf
path: plant-monitoring
cards:
- type: glance
  entities:
  - entity: sensor.water_plants_number
    name: Need watering
  - entity: sensor.fertilize_plants_number
    name: Need fertilizer
  - entity: sensor.plant_problems
    name: Plant problems


- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.sago_palm

- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.spineless_yucca

- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.rubber_plant

- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.swiss_cheese

- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.cat_palm

- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.spider_plant

- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.dumbcane

- type: custom:decluttering-card
  template: plant_status_full_picture
  variables:
  - entity: plant.dragon_tree
