#### Turns on lights on door open 
#### Starts a timer and turns them off timer runs out

##################    Entrance door    ##################
- alias: Entrance door opened
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.entrance_door
    to: 'on'
  action:
  - service: script.lights_on_smart
    data:
      entity_id: light.entrance_lights
  - service: timer.start
    entity_id: timer.entrance_door_timer

- alias: Entrance door timer finished
  mode: queued
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.entrance_door_timer
  action:
    service: light.turn_off
    entity_id: light.entrance_lights

##################    Ensuite door    ##################
- alias: Ensuite door opened
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.ensuite_door
    to: 'on'
  action:
  - service: script.lights_on_smart
    data:
      entity_id: light.ensuite_lights
  - service: timer.start
    entity_id: timer.ensuite_door_timer

- alias: Ensuite door timer finished
  mode: queued
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.ensuite_door_timer
  action:
    service: light.turn_off
    entity_id: light.ensuite_lights
