#=================================================
# Single motion sensing: Involves
# - one motion sensor
# - light level sensing
# - sun position based offsets (optional)
#=================================================

##################    Lounge    ##################
- alias: Lounge motion detected
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.lounge_activity
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.lounge_activity
    below: 18
  - condition: or
    conditions:
    - condition: sun
      after: sunset
      after_offset: "-01:00:00"
    - condition: sun
      before: sunrise
      before_offset: "01:00:00"
  action:
    service: script.lights_on_smart
    data:
      light: light.lounge_lights

- alias: Lounge motion ended
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.lounge_activity
    to: 'off'
    for:
      minutes: 20
  action:
    service: light.turn_off
    entity_id: light.lounge_lights

##################    Dining    ##################
- alias: Dining motion detected
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.dining_activity
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.dining_activity
    below: 18
  - condition: or
    conditions:
    - condition: sun
      after: sunset
      after_offset: "-01:00:00"
    - condition: sun
      before: sunrise
      before_offset: "01:00:00"
  action:
    service: script.lights_on_smart
    data:
      light: light.dining_lights

- alias: Dining motion ended
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.dining_activity
    to: 'off'
    for:
      minutes: 20
  action:
    service: light.turn_off
    entity_id: light.dining_lights

##################    Corridor    ##################
- alias: Corridor motion detected
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.corridor_activity
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.corridor_activity
    below: 18
  action:
    service: script.lights_on_smart
    data:
      light: light.corridor_lights

- alias: Corridor motion ended
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.corridor_activity
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    entity_id: light.corridor_lights

##################    Entrance    ##################
- alias: Entrance motion detected
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.entrance_activity
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.entrance_activity
    below: 18
  action:
  - service: timer.cancel
    entity_id: timer.entrance_door_timer
  - service: script.lights_on_smart
    data:
      light: light.entrance_lights

- alias: Entrance motion ended
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.entrance_activity
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    entity_id: light.entrance_lights
