#### Voice command based automations ####
- alias: Clean room with IFTTT
  id: vacuum_room_clean_with_ifttt
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: vacuum_clean_room_voice_command
  action:
    service: python_script.vacuum_clean_room
    data_template:
      room_phrase: "{{ trigger.event.data.room }}"
