####    Lounge      ####
- alias: Lounge motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.lounge_activity
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.lounge_lights

- alias: Lounge motion ended for 10 minutes
  trigger:
    platform: state
    entity_id: binary_sensor.lounge_activity
    to: 'off'
    for:
      minutes: 10
  action:
    service: light.turn_off
    entity_id: light.lounge_lights

####    Kitchen      ####
- alias: Kitchen or Living room motion detected
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_activity
    to: 'on'
  - platform: state
    entity_id: binary_sensor.kitchen_activity
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.kitchen_lights

- alias: Kitchen and Living room motion ended for 10 minutes
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_activity
    to: 'off'
    for:
      minutes: 10
  - platform: state
    entity_id: binary_sensor.kitchen_activity
    to: 'off'
    for:
      minutes: 10
  condition:
  - condition: state
    entity_id: binary_sensor.living_room_activity
    state: 'off'
  - condition: state
    entity_id: binary_sensor.kitchen_activity
    state: 'off'
  action:
    service: light.turn_off
    entity_id: light.kitchen_lights
