#=================================================
# Single motion sensing:
# Involves only one motion sensor and maybe living
# level sensing from that sensor
#=================================================

####    Lounge      ####
- alias: Lounge motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.lounge_activity
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.lounge_activity
    below: 0
  action:
    service: light.turn_on
    entity_id: light.lounge_lights

- alias: Lounge motion ended
  trigger:
    platform: state
    entity_id: binary_sensor.lounge_activity
    to: 'off'
    for:
      minutes: 10
  action:
    service: light.turn_off
    entity_id: light.lounge_lights

####    Kitchen and Living room     ####
- alias: Kitchen or Living room motion detected
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_activity
    to: 'on'
  - platform: state
    entity_id: binary_sensor.kitchen_activity
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.kitchen_lights

- alias: Kitchen and Living room motion ended
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_activity
    to: 'off'
    for:
      minutes: 10
  - platform: state
    entity_id: binary_sensor.kitchen_activity
    to: 'off'
    for:
      minutes: 10
  condition:
  - condition: state
    entity_id: binary_sensor.living_room_activity
    state: 'off'
  - condition: state
    entity_id: binary_sensor.kitchen_activity
    state: 'off'
  action:
    service: light.turn_off
    entity_id: light.kitchen_lights

####    Dining      ####
- alias: Dining motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.dining_activity
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.dining_lights

- alias: Dining motion ended
  trigger:
    platform: state
    entity_id: binary_sensor.dining_activity
    to: 'off'
    for:
      minutes: 10
  action:
    service: light.turn_off
    entity_id: light.dining_lights

####    Corridor      ####
- alias: Corridor motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.corridor_activity
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.corridor_lights

- alias: Corridor motion ended
  trigger:
    platform: state
    entity_id: binary_sensor.corridor_activity
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    entity_id: light.corridor_lights

####    Entrance      ####
- alias: Entrance motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.entrance_activity
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.entrance_lights

- alias: Entrance motion ended
  trigger:
    platform: state
    entity_id: binary_sensor.entrance_activity
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    entity_id: light.entrance_lights
