type: custom:vertical-stack-in-card
title: Room Temperatures
cards:
- type: custom:decluttering-card
  template: room_temperature_graph
  variables:
  - name: Living room
  - entity: sensor.living_room_environment

- type: custom:decluttering-card
  template: room_temperature_graph
  variables:
  - name: Bedroom
  - entity: sensor.bedroom_environment

- type: custom:decluttering-card
  template: room_temperature_graph
  variables:
  - name: Guest room
  - entity: sensor.guestroom_environment

- type: custom:decluttering-card
  template: room_temperature_graph
  variables:
  - name: Hallway
  - entity: sensor.hallway_environment
