type: custom:vertical-stack-in-card
title: Plant Monitor 1
cards:
- type: gauge
  entity: sensor.plant_monitor_1_cpu_used
  max: 100
  min: 0
  severity:
    green: 0
    yellow: 25
    red: 50
  name: CPU

- type: custom:vertical-stack-in-card
  horizontal: true
  cards:
  - type: gauge
    entity: sensor.plant_monitor_1_ram_used
    max: 4000
    min: 0
    severity:
      green: 0
      yellow: 2000
      red: 3000
    name: Memory

  - type: gauge
    entity: sensor.plant_monitor_1_etc_hostname_used
    max: 224.8
    min: 0
    severity:
      green: 0
      yellow: 120
      red: 200
    name: Internal HD

- type: custom:decluttering-card
  template: cpu_temperature_graph
  variables:
  - name: CPU temperature
  - entity: sensor.plant_monitor_1_cpu_thermal_1_temp
