type: custom:vertical-stack-in-card
title: Resources
cards:

- type: custom:vertical-stack-in-card
  horizontal: true
  cards:
  - type: gauge
    entity: sensor.home_lab_cpu_used
    max: 100
    min: 0
    severity:
      green: 0
      yellow: 25
      red: 50
    name: CPU

  - type: gauge
    entity: sensor.home_lab_ram_used
    max: 15400
    min: 0
    severity:
      green: 0
      yellow: 5000
      red: 10000
    name: Memory

- type: custom:vertical-stack-in-card
  horizontal: true
  cards:
  - type: gauge
    entity: sensor.home_lab_etc_hostname_used
    max: 916
    min: 0
    severity:
      green: 0
      yellow: 700
      red: 800
    name: Internal HD

  - type: gauge
    entity: sensor.home_lab_external_hd_used
    max: 3700
    min: 0
    severity:
      green: 0
      yellow: 2700
      red: 3500
    name: External HD
