type: custom:vertical-stack-in-card
title: Plant Monitor Indoor
cards:
- type: custom:vertical-stack-in-card
  horizontal: true
  cards:
  - type: gauge
    entity: sensor.plant_monitor_indoor_cpu_used
    max: 100
    min: 0
    severity:
      green: 0
      yellow: 25
      red: 50
    name: CPU

  - type: gauge
    entity: sensor.plant_monitor_indoor_ram_used
    max: 4000
    min: 0
    severity:
      green: 0
      yellow: 2000
      red: 3000
    name: Memory

- type: custom:vertical-stack-in-card
  horizontal: true
  cards:
  - type: gauge
    entity: sensor.plant_monitor_indoor_etc_hostname_used
    max: 224.8
    min: 0
    severity:
      green: 0
      yellow: 120
      red: 200
    name: Internal HD

  - type: glance
    entities:
    - entity: switch.plant_monitor_indoor_restart
      name: Reboot
      icon: mdi:restart
      tap_action:
        action: toggle

- type: custom:decluttering-card
  template: cpu_temperature_graph
  variables:
  - name: CPU temperature
  - entity: sensor.plant_monitor_indoor_cpu_thermal_1_temp

- type: glance
  entities:
  - entity: sensor.plant_monitor_indoor_total
    name: Processes
  - entity: sensor.plant_monitor_indoor_thread
    name: Threads
  - entity: sensor.plant_monitor_indoor_containers_active
    name: Containers
