type: custom:vertical-stack-in-card
title: CPU Temperature
cards:
- type: custom:decluttering-card
  template: cpu_temperature_graph
  variables:
  - name: Core 0
  - entity: sensor.homeassistant_core_0_temp

- type: custom:decluttering-card
  template: cpu_temperature_graph
  variables:
  - name: Core 1
  - entity: sensor.homeassistant_core_1_temp
