type: custom:vertical-stack-in-card
title: Process
cards:
- type: glance
  entities:
  - entity: sensor.homeassistant_total
    name: Total
  - entity: sensor.homeassistant_running
    name: Running
  - entity: sensor.homeassistant_sleeping
    name: Sleeping
  - entity: sensor.homeassistant_thread
    name: Threads
