title: Media
type: 'custom:vertical-stack-in-card'
cards:
- type: custom:decluttering-card
  template: media_player
  variables:
  - entity: media_player.lounge_android_tv
  - name: TV
  - icon: 'mdi:television'

- type: custom:decluttering-card
  template: media_player
  variables:
  - entity: media_player.lounge_tv_chromecast
  - name: Chromecast Ultra
  - icon: 'mdi:google-chrome'

- type: custom:decluttering-card
  template: media_player
  variables:
  - entity: media_player.kitchen_display
  - name: Kitchen
  - icon: 'mdi:monitor-dashboard'

- type: custom:decluttering-card
  template: media_player
  variables:
  - entity: media_player.hallway_speaker
  - name: Dining
  - icon: 'mdi:silverware-variant'

- type: custom:decluttering-card
  template: media_player
  variables:
  - entity: media_player.bedroom_speakers
  - name: Bedroom
  - icon: 'mdi:bed'

- type: custom:decluttering-card
  template: media_player
  variables:
  - entity: media_player.ensuite_speaker
  - name: Ensuite
  - icon: 'mdi:shower-head'
