type: custom:vertical-stack-in-card
title: Process
cards:
- type: glance
  entities:
  - entity: sensor.home_lab_total
    name: Total
  - entity: sensor.home_lab_running
    name: Running
  - entity: sensor.home_lab_sleeping
    name: Sleeping
  - entity: sensor.home_lab_thread
    name: Threads
