type: custom:vertical-stack-in-card
title: Curtains
cards:
- type: custom:decluttering-card
  template: curtain_controls
  variables:
  - entity_id: cover.living_room_curtains
  - name: Living room

- type: custom:decluttering-card
  template: curtain_controls
  variables:
  - entity_id: cover.balcony_curtain
  - name: Balcony

- type: custom:decluttering-card
  template: curtain_controls
  variables:
  - entity_id: cover.study_curtain
  - name: Study

- type: custom:decluttering-card
  template: curtain_controls
  variables:
  - entity_id: cover.bedroom_curtain
  - name: Bedroom
