type: custom:vertical-stack-in-card
title: Crypto coins
cards:
- type: custom:decluttering-card
  template: crypto_graph
  variables:
  - name: Bitcoin
  - entity: sensor.cryptoinfo_bitcoin_usd
  - icon: 'mdi:bitcoin'

- type: custom:decluttering-card
  template: crypto_graph
  variables:
  - name: Ethereum
  - entity: sensor.cryptoinfo_ethereum_usd
  - icon: 'mdi:ethereum'

- type: custom:decluttering-card
  template: crypto_graph
  variables:
  - name: Celsius Token
  - entity: sensor.cryptoinfo_celsius_degree_token_usd
  - icon: 'mdi:ethereum'

- type: custom:decluttering-card
  template: crypto_graph
  variables:
  - name: Polka Dot
  - entity: sensor.cryptoinfo_polkadot_usd
  - icon: 'mdi:ethereum'

- type: custom:decluttering-card
  template: crypto_graph
  variables:
  - name: Yarn Finance
  - entity: sensor.cryptoinfo_yearn_finance_usd
  - icon: 'mdi:ethereum'

- type: custom:decluttering-card
  template: crypto_graph
  variables:
  - name: Matic coin
  - entity: sensor.cryptoinfo_matic_network_usd
  - icon: 'mdi:ethereum'

- type: custom:decluttering-card
  template: crypto_graph
  variables:
  - name: XRP
  - entity: sensor.cryptoinfo_ripple_usd
  - icon: 'mdi:ethereum'
