type: custom:auto-entities
card:
  type: custom:battery-state-card
  title: Sensor battery levels
  sort_by_level: asc
  color_gradient:
    - "#ff0000" # red
    - "#ffff00" # yellow
    - "#00ff00" # green
filter:
  include:
  - entity_id: "sensor.*_battery_level"
