type: custom:vertical-stack-in-card
title: Docker containers
cards:
- type: glance
  entities:
  - entity: sensor.home_lab_containers_active
    name: Active
  - entity: sensor.home_lab_containers_cpu_used
    name: CPU
  - entity: sensor.home_lab_containers_ram_used
    name: RAM
