title: Media
type: 'custom:vertical-stack-in-card'
horizontal: true
cards:
- type: custom:decluttering-card
  template: battery_listing
  variables:
  - title: Motion sensors
  - include_filter: "sensor.*_activity_battery_level"

- type: custom:decluttering-card
  template: battery_listing
  variables:
  - title: Environment sensors
  - include_filter: "sensor.*_environment_battery_level"

- type: custom:decluttering-card
  template: battery_listing
  variables:
  - title: Door sensors
  - include_filter: "sensor.*_door_battery_level"
