type: custom:vertical-stack-in-card
title: Plant Monitor Outdoor
cards:
- type: custom:vertical-stack-in-card
  horizontal: true
  cards:
  - type: gauge
    entity: sensor.plant_monitor_outdoor_cpu_used
    max: 100
    min: 0
    severity:
      green: 0
      yellow: 25
      red: 50
    name: CPU

  - type: gauge
    entity: sensor.plant_monitor_outdoor_ram_used
    max: 4000
    min: 0
    severity:
      green: 0
      yellow: 2000
      red: 3000
    name: Memory

- type: custom:vertical-stack-in-card
  horizontal: true
  cards:
  - type: gauge
    entity: sensor.plant_monitor_outdoor_etc_hostname_used
    max: 14.7
    min: 0
    severity:
      green: 0
      yellow: 6
      red: 10
    name: Internal HD

  - type: glance
    entities:
    - entity: switch.plant_monitor_outdoor_restart
      name: Reboot
      icon: mdi:restart
      tap_action:
        action: toggle
        confirmation:
          text: Are you sure you want to restart?

- type: custom:decluttering-card
  template: cpu_temperature_graph
  variables:
  - name: CPU temperature
  - entity: sensor.plant_monitor_outdoor_cpu_thermal_1_temp

- type: glance
  entities:
  - entity: sensor.plant_monitor_outdoor_total
    name: Processes
  - entity: sensor.plant_monitor_outdoor_thread
    name: Threads
  - entity: sensor.plant_monitor_outdoor_containers_active
    name: Containers
