title: Sensor battery levels
type: 'custom:vertical-stack-in-card'
cards:
- type: custom:decluttering-card
  template: battery_listing
  variables:
  - title: Motion
  - include_filter: "sensor.*_activity_battery_level"
  - renameFrom: activity
  - renameFrom2: Battery Level
  - renameFrom3: Motion

- type: custom:decluttering-card
  template: battery_listing
  variables:
  - title: Environment
  - include_filter: "sensor.*_environment_battery_level"
  - renameFrom: environment
  - renameFrom2: Battery Level

- type: custom:decluttering-card
  template: battery_listing
  variables:
  - title: Door
  - include_filter: "sensor.*_door_battery_level"
  - renameFrom: door
  - renameFrom2: Battery Level

- type: custom:decluttering-card
  template: battery_listing
  variables:
  - title: Plant
  - include_filter: "sensor.miflora_*_battery"
  - renameFrom: MiFlora_
  - renameFrom2: Battery
  - renameFrom3: _
  - renameTo3: " "
  - renameFrom4: _
  - renameTo4: " "
