type: custom:vertical-stack-in-card
title: Home Lab
cards:
- type: custom:vertical-stack-in-card
  horizontal: true
  cards:
  - type: gauge
    entity: sensor.home_lab_cpu_used
    max: 100
    min: 0
    severity:
      green: 0
      yellow: 25
      red: 50
    name: CPU

  - type: gauge
    entity: sensor.home_lab_ram_used
    max: 15400
    min: 0
    severity:
      green: 0
      yellow: 5000
      red: 10000
    name: Memory

- type: custom:vertical-stack-in-card
  horizontal: true
  cards:
  - type: gauge
    entity: sensor.home_lab_etc_hostname_used
    max: 916
    min: 0
    severity:
      green: 0
      yellow: 700
      red: 800
    name: Internal HD

  - type: gauge
    entity: sensor.home_lab_external_hd_used
    max: 3700
    min: 0
    severity:
      green: 0
      yellow: 2700
      red: 3500
    name: External HD

- type: custom:decluttering-card
  template: cpu_temperature_graph
  variables:
  - name: Temperature - Core 0
  - entity: sensor.home_lab_core_0_temp

- type: custom:decluttering-card
  template: cpu_temperature_graph
  variables:
  - name: Temperature - Core 1
  - entity: sensor.home_lab_core_1_temp

- type: glance
  entities:
  - entity: sensor.home_lab_total
    name: Processes
  - entity: sensor.home_lab_thread
    name: Threads
  - entity: sensor.home_lab_containers_active
    name: Containers
