title: Sensor battery levels
type: 'custom:vertical-stack-in-card'
cards:
- type: custom:decluttering-card
  template: battery_listing
  variables:
  - title: motion
  - include_filter: "sensor.*_activity_battery_level"

- type: custom:decluttering-card
  template: battery_listing
  variables:
  - title: environment
  - include_filter: "sensor.*_environment_battery_level"

- type: custom:decluttering-card
  template: battery_listing
  variables:
  - title: door
  - include_filter: "sensor.*_door_battery_level"
