
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

hue:
  bridges:
    - host: !secret philips_hue_hub_ip 
      allow_hue_groups: false
      allow_unreachable: true