homeassistant:
  auth_providers:
  - type: homeassistant

  name: !secret home_name
  temperature_unit: !secret temperature_unit
  time_zone: !secret time_zone
  unit_system: !secret unit_system

  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home

  customize: !include_dir_merge_list customize
  customize_glob: !include_dir_merge_list customize_glob
  packages: !include_dir_named packages

# Data saving policy
recorder:
  purge_keep_days: 10

# Text to speech
tts:
- platform: google_translate

logbook: !include logbook.yaml
history: !include history.yaml
lovelace: !include lovelace.yaml

light: !include lights.yaml
switch: !include_dir_merge_list switches
automation: !include_dir_merge_list automations
script: !include_dir_merge_list scripts

group: !include groups.yaml
scene: !include scenes.yaml
frontend: !include frontend.yaml

python_script:
sun:
person:
mobile_app:
cloud:
  google_actions: !include google_actions.yaml

hue:
  bridges:
  - host: !secret philips_hue_hub_ip 
    allow_hue_groups: false
    allow_unreachable: true

vacuum:
- platform: xiaomi_miio
  name: Kevin clean
  host: !secret robot_vacuum_host
  token: !secret robot_vacuum_token

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: !secret tuya_country_code

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  mode: local
  devices:
    100094996f:
      device_class: light
      name: Balcony light
    1000c1872c:
      device_class: light
      name: Cooktop lights

hacs:
  token: !secret github_personal_token

media_player:
- platform: androidtv
  name: Lounge TV
  host: !secret android_tv_host
  adbkey: "/config/adbkey"

notify:
- platform: nfandroidtv
  name: Lounge TV
  host: !secret android_tv_host
