
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Data saving policy
recorder:
  purge_keep_days: 10

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

cloud:
  google_actions:
    filter:
      # Disconnect Hue in Google assistant
      include_domains:
        - light

      # All media players in the home are google cast enabled. They will appear in the google assistant
      exclude_domains:
        - media_player

hue:
  bridges:
    - host: !secret philips_hue_hub_ip 
      allow_hue_groups: false
      allow_unreachable: true

vacuum:
  - platform: xiaomi_miio
    name: kevin_clean
    host: !secret robot_vacuum_host
    token: !secret robot_vacuum_token

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: !secret tuya_country_code

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  mode: local
  devices:
    100094996f:
      device_class: light
      name: Balcony light
    1000c1872c:
      device_class: light
      name: Cooktop lights

hacs:
  token: !secret github_personal_token
