
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

cloud:
  google_actions:
    filter:
      # Disconnect Hue in Google assistant
      include_domains:
        - light
        
      # All media players in the home are google cast enabled. They will appear in the google assistant
      exclude_domains:
        - media_player

hue:
  bridges:
    - host: !secret philips_hue_hub_ip 
      allow_hue_groups: false
      allow_unreachable: true