homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24

  name: !secret home_name
  temperature_unit: !secret temperature_unit
  time_zone: !secret time_zone
  unit_system: !secret unit_system

  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home

  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  packages: !include_dir_named packages

# Data saving policy
recorder:
  purge_keep_days: 10

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend: !include frontend.yaml
logbook: !include logbook.yaml
history: !include history.yaml
lovelace: !include lovelace.yaml
light: !include lights.yaml
switch: !include switches.yaml

cloud:
  google_actions: !include google_actions.yaml

hue:
  bridges:
    - host: !secret philips_hue_hub_ip 
      allow_hue_groups: false
      allow_unreachable: true

vacuum:
  - platform: xiaomi_miio
    name: Kevin clean
    host: !secret robot_vacuum_host
    token: !secret robot_vacuum_token

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: !secret tuya_country_code

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  mode: local
  devices:
    100094996f:
      device_class: light
      name: Balcony light
    1000c1872c:
      device_class: light
      name: Cooktop lights

hacs:
  token: !secret github_personal_token

python_script:
sun:
person:

media_player:
  - platform: androidtv
    name: Lounge TV
    host: !secret android_tv_host

notify:
  - platform: nfandroidtv
    name: Lounge TV
    host: !secret android_tv_host
