# Initial brigtness to use for lights when they are turned on
contextual_brightness:
  name: Brightness
  initial: 200
  min: 0
  max: 255
  step: 1

contextual_color_red:
  name: Brightness
  initial: 200
  min: 0
  max: 255
  step: 1

contextual_color_green:
  name: Brightness
  initial: 200
  min: 0
  max: 255
  step: 1

contextual_color_blue:
  name: Brightness
  initial: 200
  min: 0
  max: 255
  step: 1
