# Grouping all the lights here
- platform: group
  name: Kitchen lights
  id: kitchen_lights
  entities:
  - light.kitchen_light_1
  - light.kitchen_light_2
  - light.kitchen_light_3

- platform: group
  name: Dining lights
  id: dining_lights
  entities:
  - light.dining_light_1
  - light.dining_light_2

- platform: group
  name: Lounge lights
  id: lounge_lights
  entities:
  - light.lounge_light_1
  - light.lounge_light_2
  - light.lounge_light_3
  - light.lounge_light_4
  - light.lounge_light_5
  - light.lounge_light_6

- platform: group
  name: Living room lights
  id: living_room_lights
  entities:
  - light.lounge_lights
  - light.kitchen_lights
  - light.dining_lights

- platform: group
  name: Entrance lights
  id: entrance_lights
  entities:
  - light.entrance_light_1
  - light.entrance_light_2
  - light.entrance_light_3

- platform: group
  name: Corridor lights
  id: corridor_lights
  entities:
  - light.corridor_light_1
  - light.corridor_light_2
  - light.corridor_light_3
