title: Home

views:
- title: Home

  badges:
  - entity: sun.sun
  - entity: person.praveen_pendyala

  cards:
  - type: 'custom:vacuum-card'
    entity: vacuum.kevin_clean
    actions:
    - icon: 'mdi:silverware-spoon'
      name: Clean kitchen
      service: script.vacuum_clean_kitchen
    - icon: 'mdi:silverware-fork-knife'
      name: Clean dining
      service: script.vacuum_clean_dining
    - icon: 'mdi:sofa'
      name: Clean living room
      service: script.vacuum_clean_living_room
    - icon: 'mdi:bed-empty'
      name: Clean bedroom
      service: script.vacuum_clean_bedroom
    - icon: 'mdi:face'
      name: Clean guest room
      service: script.vacuum_clean_guestroom
    - icon: 'mdi:laravel'
      name: Clean guest room
      service: script.vacuum_clean_hallway
    stats:
      cleaning:
      - attribute: cleaned_area
        subtitle: Cleaning area
        unit: m2
      - attribute: cleaning_time
        subtitle: Cleaning time
        unit: minutes
      default:
      - attribute: filter_left
        subtitle: Filter
        unit: hours
      - attribute: side_brush_left
        subtitle: Side brush
        unit: hours
      - attribute: main_brush_left
        subtitle: Main brush
        unit: hours
      - attribute: sensor_dirty_left
        subtitle: Sensors
        unit: hours
