cover_button:
  styles:
    card:
    - height: 80px

cover_title_button:
  template: cover_button
  tap_action:
    action: more-info
  show_icon: false
  show_state: true
  show_name: true
  styles:
    name:
    - font-size: 16px
    label:
    - font-size: 12px
    - color: blue

cover_control_button:
  template: cover_button
  variables:
    action_service: cover.open_cover
  show_icon: true
  show_state: false
  show_name: false
  styles:
    card:
    - width: 80px
  tap_action:
    action: call-service
    service: '[[[ return variables.action_service ]]]'
  hold_action:
    action: more-info
