curtain_control_button:
  variables:
    action_service: cover.open_cover
  show_state: false
  styles:
    card:
      - height: 80px
      - width: 80px
      - font-size: 12px
      - font-weight: bold
  tap_action:
    action: call-service
    service: '[[[ return variables.action_service ]]]'
  hold_action:
    action: more-info
