cover_button:
  show_state: false
  styles:
    card:
    - height: 60px

cover_title_button:
  template: cover_button
  tap_action:
    action: more-info
  show_icon: false
  show_name: true
  styles:
    name:
    - justify-self: start
    - padding-left: 16px
    - font-size: 16px

cover_control_button:
  template: cover_button
  variables:
    action_service: cover.open_cover
  show_icon: true
  show_name: false
  styles:
    card:
    - width: 80px
  tap_action:
    action: call-service
    service: '[[[ return variables.action_service ]]]'
    service_data:
      entity_id: '[[[ return variables.entity ]]]'
  hold_action:
    action: more-info
