curtain_controls:
  default:
  - name: Curtain
  - entity: ''
  card:
    type: custom:vertical-stack-in-card
    horizontal: true
    cards:
    - type: custom:button-card
      template: cover_title_button
      name: '[[name]]'
      entity: '[[entity]]'

    - type: custom:button-card
      template: cover_control_button
      name: Open
      entity: '[[entity]]'
      variables:
        action_service: cover.open_cover
        entity: '[[entity]]'
      icon: mdi:code-tags

    - type: custom:button-card
      template: cover_control_button
      name: Stop
      entity: '[[entity]]'
      variables:
        action_service: cover.stop_cover
        entity: '[[entity]]'
      icon: mdi:stop-circle-outline

    - type: custom:button-card
      template: cover_control_button
      name: Close
      entity: '[[entity]]'
      variables:
        action_service: cover.close_cover
        entity: '[[entity]]'
      icon: mdi:arrow-collapse-horizontal

media_player:
  default:
  - name: Speaker
  - entity_id: ''
  - icon: mdi:speaker
  card:
    type: custom:mini-media-player
    entity: '[[entity]]'
    icon: '[[icon]]'
    artwork: cover
    name: '[[name]]'
    hide:
      power: true

battery_listing:
  default:
  - title: Battery levels
  - include_filter: "sensor.*_battery_level"
  - renameFrom: 'Battery level'
  - renameTo: ''
  - renameFrom2: 'Battery'
  - renameTo2: ''
  - renameFrom3: 'Battery'
  - renameTo3: ''
  - renameFrom4: 'battery'
  - renameTo4: ''
  card:
    type: custom:auto-entities
    card:
      type: custom:battery-state-card
      title: '[[title]]'
      sort_by_level: asc
      bulk_rename:
      - from: '[[renameFrom]]'
        to: '[[renameTo]]'
      - from: '[[renameFrom2]]'
        to: '[[renameTo2]]'
      - from: '[[renameFrom3]]'
        to: '[[renameTo3]]'
      - from: '[[renameFrom4]]'
        to: '[[renameTo4]]'
      color_gradient:
      - "#ff0000" # red
      - "#ffff00" # yellow
      - "#00ff00" # green
    filter:
      include:
      - entity_id: '[[include_filter]]'

sensor_graph:
  default:
  - name: Sensor Graph
  - entity: ''
  - icon: 'mdi:chart-bell-curve'
  - color_0: '#00a9f4' # blue shade
  - color_1: '#69b932' # green shade
  - color_2: '#fdcf57' # yellow shade
  - color_3: '#e85342' # red shade
  - threshold_0: 0
  - threshold_1: 20
  - threshold_2: 40
  - threshold_3: 60
  card:
    type: 'custom:mini-graph-card'
    name: '[[name]]'
    aggregate_func: avg
    animate: true
    color_thresholds:
    - color: '[[color_0]]'
      value: '[[threshold_0]]'
    - color: '[[color_1]]'
      value: '[[threshold_1]]'
    - color: '[[color_2]]'
      value: '[[threshold_2]]'
    - color: '[[color_3]]'
      value: '[[threshold_3]]'
    color_thresholds_transition: smooth
    decimals: 0
    entities:
    - entity: '[[entity]]'
      name: '[[name]]'
    hours_to_show: 24
    icon: '[[icon]]'
    line_width: 3
    points_per_hour: 1

cpu_temperature_graph:
  default:
  - name: CPU Temperature
  - entity: ''
  card:
    type: custom:decluttering-card
    template: sensor_graph
    variables:
    - name: '[[name]]'
    - entity: '[[entity]]'
    - icon: 'mdi:thermometer-lines'
    - threshold_0: 35
    - threshold_1: 48
    - threshold_2: 56
    - threshold_3: 65

room_temperature_graph:
  default:
  - name: Room Temperature
  - entity: ''
  card:
    type: custom:decluttering-card
    template: sensor_graph
    variables:
    - name: '[[name]]'
    - entity: '[[entity]]'
    - icon: 'mdi:thermometer'
    - threshold_0: 20
    - threshold_1: 25
    - threshold_2: 30
    - threshold_3: 36

room_humidity_graph:
  default:
  - name: Room Humidity
  - entity: ''
  card:
    type: custom:decluttering-card
    template: sensor_graph
    variables:
    - name: '[[name]]'
    - entity: '[[entity]]'
    - icon: 'mdi:water-percent'
    - threshold_0: 20
    - threshold_1: 30
    - threshold_2: 40
    - threshold_3: 50 
    - color_0: '#e85342' # red shade
    - color_1: '#fdcf57' # yellow shade
    - color_2: '#69b932' # green shade
    - color_3: '#00a9f4' # blue shade

crypto_graph:
  default:
  - name: Asset
  - entity: ''
  - icon: 'mdi:bitcoin'
  card:
    type: 'custom:mini-graph-card'
    name: '[[name]]'
    aggregate_func: avg
    animate: true
    decimals: 1
    entities:
    - entity: '[[entity]]'
      name: '[[name]]'
    hours_to_show: 168
    group_by: date
    icon: '[[icon]]'
    line_width: 3

stock_graph:
  default:
  - entity: ''
  card:
    type: 'custom:mini-graph-card'
    aggregate_func: avg
    animate: true
    decimals: 1
    entities:
    - entity: '[[entity]]'
    hours_to_show: 168
    group_by: date
    icon: mdi:chart-line
    line_width: 3

plant_status_full_picture:
  default:
  - entity: ''
  card:
    type: plant-status
    entity: '[[entity]]'
    style: |
      .has-plant-image .banner {
        padding-top: 100% !important;
      }
