curtain_controls:
  default:
    - name: Curtain
    - entity_id: cover.balcony_curtain
  card:
    type: horizontal-stack
    cards:
    - type: custom:button-card
      template: cover_title_button
      name: '[[name]]'
      entity: '[[entity_id]]'

    - type: custom:button-card
      template: cover_control_button
      name: Open
      entity: '[[entity_id]]'
      variables:
        action_service: cover.open_cover
      icon: mdi:code-tags

    - type: custom:button-card
      template: cover_control_button
      name: Stop
      entity: '[[entity_id]]'
      variables:
        action_service: cover.stop_cover
      icon: mdi:stop-circle-outline

    - type: custom:button-card
      template: cover_control_button
      name: Close
      entity: '[[entity_id]]'
      variables:
        action_service: cover.close_cover
      icon: mdi:arrow-collapse-horizontal
