curtain_controls:
  default:
    - name: Curtain
    - entity: cover.balcony_curtain
  card:
    type: custom:vertical-stack-in-card
    horizontal: true
    cards:
    - type: custom:button-card
      template: cover_title_button
      name: '[[name]]'
      entity: '[[entity]]'

    - type: custom:button-card
      template: cover_control_button
      name: Open
      entity: '[[entity]]'
      variables:
        action_service: cover.open_cover
        entity: '[[entity]]'
      icon: mdi:code-tags

    - type: custom:button-card
      template: cover_control_button
      name: Stop
      entity: '[[entity]]'
      variables:
        action_service: cover.stop_cover
        entity: '[[entity]]'
      icon: mdi:stop-circle-outline

    - type: custom:button-card
      template: cover_control_button
      name: Close
      entity: '[[entity]]'
      variables:
        action_service: cover.close_cover
        entity: '[[entity]]'
      icon: mdi:arrow-collapse-horizontal

media_player:
  default:
    - name: Kitchen
    - entity_id: media_player.kitchen_display
    - icon: mdi:speaker
  card:
    type: custom:mini-media-player
    entity: '[[entity]]'
    icon: '[[icon]]'
    artwork: cover
    name: '[[name]]'
    hide:
      power: true

battery_listing:
  default:
    - title: Battery levels
    - include_filter: "sensor.*_activity_battery_level"
    - rename: ''
    - rename2: ''
  card:
    type: custom:auto-entities
    card:
      type: custom:battery-state-card
      title: '[[title]]'
      sort_by_level: asc
      bulk_rename:
      - from: 'Battery Level'
        to: ''
      - from: '[[title]]'
        to: ''
      - from: '[[rename]]'
        to: ''
      - from: '[[rename2]]'
        to: ''
      color_gradient:
      - "#ff0000" # red
      - "#ffff00" # yellow
      - "#00ff00" # green
    filter:
      include:
      - entity_id: '[[include_filter]]'
