curtain_controls:
  default:
  - name: Curtain
  - entity: ''
  card:
    type: custom:vertical-stack-in-card
    horizontal: true
    cards:
    - type: custom:button-card
      template: cover_title_button
      name: '[[name]]'
      entity: '[[entity]]'

    - type: custom:button-card
      template: cover_control_button
      name: Open
      entity: '[[entity]]'
      variables:
        action_service: cover.open_cover
        entity: '[[entity]]'
      icon: mdi:code-tags

    - type: custom:button-card
      template: cover_control_button
      name: Stop
      entity: '[[entity]]'
      variables:
        action_service: cover.stop_cover
        entity: '[[entity]]'
      icon: mdi:stop-circle-outline

    - type: custom:button-card
      template: cover_control_button
      name: Close
      entity: '[[entity]]'
      variables:
        action_service: cover.close_cover
        entity: '[[entity]]'
      icon: mdi:arrow-collapse-horizontal

media_player:
  default:
  - name: Speaker
  - entity_id: ''
  - icon: mdi:speaker
  card:
    type: custom:mini-media-player
    entity: '[[entity]]'
    icon: '[[icon]]'
    artwork: cover
    name: '[[name]]'
    hide:
      power: true

battery_listing:
  default:
  - title: Battery levels
  - include_filter: "sensor.*_battery_level"
  - rename: ''
  - rename2: ''
  card:
    type: custom:auto-entities
    card:
      type: custom:battery-state-card
      title: '[[title]]'
      sort_by_level: asc
      bulk_rename:
      - from: 'Battery Level'
        to: ''
      - from: '[[title]]'
        to: ''
      - from: '[[rename]]'
        to: ''
      - from: '[[rename2]]'
        to: ''
      color_gradient:
      - "#ff0000" # red
      - "#ffff00" # yellow
      - "#00ff00" # green
    filter:
      include:
      - entity_id: '[[include_filter]]'

sensor_graph:
  default:
  - name: Sensor Graph
  - entity: ''
  - icon: 'mdi:chart-bell-curve'
  - color_0: '#00a9f4' # blue shade
  - color_1: '#69b932' # green shade
  - color_2: '#fdcf57' # yellow shade
  - color_3: '#e85342' # red shade
  - threshold_0: 0
  - threshold_1: 20
  - threshold_2: 40
  - threshold_3: 60
  card:
    type: 'custom:mini-graph-card'
    name: '[[name]]'
    aggregate_func: avg
    animate: true
    color_thresholds:
    - color: '[[color_0]]'
      value: '[[threshold_0]]'
    - color: '[[color_1]]'
      value: '[[threshold_1]]'
    - color: '[[color_2]]'
      value: '[[threshold_2]]'
    - color: '[[color_3]]'
      value: '[[threshold_3]]'
    color_thresholds_transition: smooth
    decimals: 0
    entities:
    - entity: '[[entity]]'
      name: '[[name]]'
    hours_to_show: 24
    icon: '[[icon]]'
    line_width: 3
    points_per_hour: 1

cpu_temperature_graph:
  default:
  - name: CPU Temperature
  - entity: ''
  card:
    type: custom:decluttering-card
    template: sensor_graph
    variables:
    - name: '[[name]]'
    - entity: '[[entity]]'
    - icon: 'mdi:thermometer-lines'
    - threshold_0: 30
    - threshold_1: 40
    - threshold_2: 50
    - threshold_3: 60

room_temperature_graph:
  default:
  - name: Room Temperature
  - entity: ''
  card:
    type: custom:decluttering-card
    template: sensor_graph
    variables:
    - name: '[[name]]'
    - entity: '[[entity]]'
    - icon: 'mdi:thermometer'
    - threshold_0: 10
    - threshold_1: 20
    - threshold_2: 25
    - threshold_3: 30

room_humidity_graph:
  default:
  - name: Room Humidity
  - entity: ''
  card:
    type: custom:decluttering-card
    template: sensor_graph
    variables:
    - name: '[[name]]'
    - entity: '[[entity]]'
    - icon: 'mdi:water-percent'
    - threshold_0: 20
    - threshold_1: 30
    - threshold_2: 40
    - threshold_3: 50 
    - color_0: '#e85342' # red shade
    - color_1: '#fdcf57' # yellow shade
    - color_2: '#69b932' # green shade
    - color_3: '#00a9f4' # blue shade
