chilli_plant:
  sensors:
    moisture: sensor.miflora_chilli_plant_moisture
    battery: sensor.miflora_chilli_plant_battery
    temperature: sensor.miflora_chilli_plant_temperature
    conductivity: sensor.miflora_chilli_plant_conductivity
    brightness: sensor.miflora_chilli_plant_light
  min_moisture: 15
  max_moisture: 60
  min_conductivity: 150
  max_conductivity: 2000
  min_brightness: 3000
  max_brightness: 95000
  min_temperature: 10
  max_temperature: 35

cherry_tomato:
  sensors:
    moisture: sensor.miflora_cherry_tomato_moisture
    battery: sensor.miflora_cherry_tomato_battery
    temperature: sensor.miflora_cherry_tomato_temperature
    conductivity: sensor.miflora_cherry_tomato_conductivity
    brightness: sensor.miflora_cherry_tomato_light
  min_moisture: 20
  max_moisture: 65
  min_conductivity: 350
  max_conductivity: 2000
  min_brightness: 3500
  max_brightness: 130000
  min_temperature: 10
  max_temperature: 32
  
lavender:
  sensors:
    moisture: sensor.miflora_lavender_moisture
    battery: sensor.miflora_lavender_battery
    temperature: sensor.miflora_lavender_temperature
    conductivity: sensor.miflora_lavender_conductivity
    brightness: sensor.miflora_lavender_light
  min_moisture: 15
  max_moisture: 60
  min_conductivity: 350
  max_conductivity: 2000
  min_brightness: 3000
  max_brightness: 70000
  min_temperature: 5
  max_temperature: 35

mini_roses:
  sensors:
    moisture: sensor.miflora_mini_roses_moisture
    battery: sensor.miflora_mini_roses_battery
    temperature: sensor.miflora_mini_roses_temperature
    conductivity: sensor.miflora_mini_roses_conductivity
    brightness: sensor.miflora_mini_roses_light
  min_moisture: 16
  max_moisture: 75
  min_conductivity: 425
  max_conductivity: 2000
  min_brightness: 3000
  max_brightness: 60000
  min_temperature: 8
  max_temperature: 35

parsley_coriander:
  sensors:
    moisture: sensor.miflora_parsley_coriander_moisture
    battery: sensor.miflora_parsley_coriander_battery
    temperature: sensor.miflora_parsley_coriander_temperature
    conductivity: sensor.miflora_parsley_coriander_conductivity
    brightness: sensor.miflora_parsley_coriander_light
  min_moisture: 15
  max_moisture: 60
  min_conductivity: 350
  max_conductivity: 2000
  min_brightness: 4000
  max_brightness: 50000
  min_temperature: 5
  max_temperature: 30

basil_cinnamon:
  sensors:
    moisture: sensor.miflora_basil_cinnamon_moisture
    battery: sensor.miflora_basil_cinnamon_battery
    temperature: sensor.miflora_basil_cinnamon_temperature
    conductivity: sensor.miflora_basil_cinnamon_conductivity
    brightness: sensor.miflora_basil_cinnamon_light
  min_moisture: 15
  max_moisture: 60
  min_conductivity: 350
  max_conductivity: 2000
  min_brightness: 2500
  max_brightness: 60000
  min_temperature: 8
  max_temperature: 32

japanese_cypress:
  sensors:
    moisture: sensor.miflora_japanese_cypress_moisture
    battery: sensor.miflora_japanese_cypress_battery
    temperature: sensor.miflora_japanese_cypress_temperature
    conductivity: sensor.miflora_japanese_cypress_conductivity
    brightness: sensor.miflora_japanese_cypress_light
  min_moisture: 15
  max_moisture: 60
  min_conductivity: 350
  max_conductivity: 2000
  min_brightness: 3500
  max_brightness: 50000
  min_temperature: 5
  max_temperature: 35

aleo_vera:
  sensors:
    moisture: sensor.miflora_aleo_vera_moisture
    battery: sensor.miflora_aleo_vera_battery
    temperature: sensor.miflora_aleo_vera_temperature
    conductivity: sensor.miflora_aleo_vera_conductivity
    brightness: sensor.miflora_aleo_vera_light
  min_moisture: 7
  max_moisture: 50
  min_conductivity: 300
  max_conductivity: 1000
  min_brightness: 3000
  max_brightness: 70000
  min_temperature: 8
  max_temperature: 35
