homeassistant:
  auth_providers:
  - type: homeassistant

  name: !secret home_name
  temperature_unit: !secret temperature_unit
  time_zone: !secret time_zone
  unit_system: !secret unit_system

  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home

  packages: !include_dir_named packages
  customize: !include customize.yaml

# Data saving policy
recorder:
  db_url: !secret database_url
  purge_keep_days: 10

# Text to speech
tts:
- platform: google_translate

logbook: !include logbook.yaml
history: !include history.yaml
lovelace: !include lovelace.yaml

light: !include lights.yaml
cover: !include covers.yaml
automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
input_select: !include input_selects.yaml
input_number: !include input_numbers.yaml
input_boolean: !include input_booleans.yaml
timer: !include timers.yaml
sensor: !include_dir_merge_list sensors

group: !include groups.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
frontend: !include frontend.yaml

person: !include persons.yaml
plant: !include_dir_merge_named plants
mobile_app:
cloud:
  google_actions: !include google_actions.yaml
python_script:
sun:

hue:
  bridges:
  - host: !secret philips_hue_hub_ip 
    allow_hue_groups: false
    allow_unreachable: true

vacuum:
- platform: xiaomi_miio
  name: Kevin clean
  host: !secret robot_vacuum_host
  token: !secret robot_vacuum_token

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: !secret tuya_country_code

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  mode: local
  devices:
    100094996f:
      device_class: light
      name: Balcony light
    1000c1872c:
      device_class: light
      name: Microwave light
    1000b7ee2a:
      device_class: light
      name: Cooking lights

hacs:
  token: !secret github_personal_token

media_player:
- platform: androidtv
  name: Lounge Android TV
  host: !secret android_tv_host
  adbkey: /config/adbkey
  exclude_unnamed_apps: true
  apps:
    com.google.android.tvlauncher: "Home"
    com.google.android.youtube.tv: "Youtube"
    com.amazon.amazonvideo.livingroom: "Amazon Prime Video"
    com.plexapp.android: "Plex"
    com.netflix.ninja: "Netflix"
    com.google.android.tv: "Live Channels"
    pct.droid.tv: "Popcorn Time"

notify:
- platform: nfandroidtv
  name: Lounge TV
  host: !secret android_tv_host

glances:
- name: Home Lab
  host: !secret home_assistant_host
- name: Plant Monitor 1
  host: !secret plant_monitor_1_host
- name: Plant Monitor 2
  host: !secret plant_monitor_2_host

transmission:
  host: !secret home_assistant_host
  port: 9091
  name: Torrent client
  username: !secret transmission_username
  password: !secret transmission_password

mqtt:
  broker: !secret home_assistant_host
  discovery: true
  discovery_prefix: homeassistant
