homeassistant:
  auth_providers:
  - type: homeassistant

  name: !secret home_name
  temperature_unit: !secret temperature_unit
  time_zone: !secret time_zone
  unit_system: !secret unit_system

  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home

  packages: !include_dir_named packages
  customize: !include customize.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.19.0.1

config_editor:

# Data saving policy
recorder:
  db_url: !secret database_url
  purge_keep_days: 10

# Text to speech
tts:
- platform: google_translate

logbook: !include logbook.yaml
history: !include history.yaml
lovelace: !include lovelace.yaml

light: !include lights.yaml
cover: !include covers.yaml
switch: !include switches.yaml
automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
input_select: !include input_selects.yaml
input_number: !include input_numbers.yaml
input_boolean: !include input_booleans.yaml
timer: !include timers.yaml
#sensor: !include_dir_merge_list sensors

group: !include groups.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
frontend: !include frontend.yaml

device_tracker:
- platform: ping
  hosts:
    jade_phone: 192.168.1.119
    edward_phone: 192.168.1.129
person: !include persons.yaml
plant: !include_dir_merge_named plants
mobile_app:
#cloud:
#  google_actions: !include google_actions.yaml
python_script:
sun:

google_assistant:
  project_id: home-lab-6dcf2
  service_account: !include home-lab-google-service-account.json
  report_state: true
  exposed_domains:
    - switch
    - light

hue:
  bridges:
  - host: !secret philips_hue_hub_ip 
    allow_hue_groups: false
    allow_unreachable: true

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  reload: always
  devices:
    100094996f:
      device_class: light
      name: Balcony light
    1000c1872c:
      device_class: light
      name: Microwave light
    1000b7ee2a:
      device_class: light
      name: Cooking lights

media_player:
- platform: androidtv
  name: Lounge Android TV
  host: !secret android_tv_host
  adbkey: /config/keys/adbkey
  exclude_unnamed_apps: true
  apps:
    com.google.android.tvlauncher: "Home"
    com.google.android.youtube.tv: "Youtube"
    com.amazon.amazonvideo.livingroom: "Amazon Prime Video"
    com.plexapp.android: "Plex"
    com.netflix.ninja: "Netflix"
    com.google.android.tv: "Live Channels"
    pct.droid.tv: "Popcorn Time"

notify:
- platform: nfandroidtv
  name: Lounge TV
  host: !secret android_tv_host

glances:
- name: Home Lab
  host: !secret home_assistant_host

transmission:
  host: !secret home_assistant_host
  port: 9091
  name: Torrent client
  username: !secret transmission_username
  password: !secret transmission_password

