# Persons
person.praveen:
  entity_picture: "/local/images/praveen.jpg"
person.mar:
  entity_picture: "/local/images/mar.jpg"

# Plants
plant.sago_palm:
  friendly_name: Sago Palm
  entity_picture: "/local/images/plants/sago_palm.jpg"

plant.spineless_yucca:
  friendly_name: Spinless Yucca
  entity_picture: "/local/images/plants/spineless_yucca.jpg"

plant.rubber_plant:
  friendly_name: Rubber Plant
  entity_picture: "/local/images/plants/rubber_plant.jpg"

plant.swiss_cheese:
  friendly_name: Swiss Cheese
  entity_picture: "/local/images/plants/swiss_cheese.jpg"

plant.cat_palm:
  friendly_name: Cat Palm
  entity_picture: "/local/images/plants/cat_palm.jpg"

plant.spider_plant:
  friendly_name: Spider Plant
  entity_picture: "/local/images/plants/spider_plant.jpg"

plant.dumbcane:
  friendly_name: Dumbcane
  entity_picture: "/local/images/plants/dumbcane.jpg"

plant.dragon_tree:
  friendly_name: Dragon Tree
  entity_picture: "/local/images/plants/dragon_tree.jpg"
