filter:
  # Disconnect Hue in Google assistant to avoid duplicate lights
  # I see HA as better than Hue because it won't pollute with so many scenes in Google home
  include_domains:
  - vacuum

  include_entities:
  # Lights
  - light.kitchen_lights
  - light.cooktop_light
  - light.dining_lights
  - light.lounge_lights

  - light.bedroom_lights
  - light.ensuite_lights

  - light.entrance_lights
  - light.corridor_lights

  - light.balcony_light

  - light.electronics_storage_light
  - light.shoe_storage_light

  # Curtains
  - cover.bedroom_curtain
  - cover.study_curtain
  - cover.balcony_curtain
  - cover.living_room_curtains

  # All media players in the home are google cast enabled. They will appear in the google assistant
  exclude_domains:
  - light
  - media_player

entity_config:
  ##### Robo vacuum #####
  vacuum.kevin_clean:
    name: Robo Vacuum
    aliases:
    - Kevin clean
    - Robovac
    room: Living room


  ##### Lights #####
  light.kitchen_lights:
    room: Living room
  light.cooktop_light:
    room: Living room
  light.dining_lights:
    room: Living room
  light.lounge_lights:
    room: Living room

  light.corridor_lights:
    room: Hallway
  light.entrance_lights:
    room: Hallway

  light.bedroom_lights:
    room: Bedroom
  light.ensuite_lights:
    room: Ensuite

  light.balcony_light:
    room: Balcony

  light.electronics_storage_light:
    room: Storage
  light.shoe_storage_light:
    room: Storage

  ##### Covers #####
  cover.living_room_curtains:
    room: Living room
  cover.study_curtain:
    room: Living room
  cover.balcony_curtain:
    room: Living room

  cover.bedroom_curtain:
    room: Bedroom

