praveen_home:
  name: Indicates Praveen is home
  icon: mdi:face-profile

mar_home:
  name: Indicates Mar is home
  icon: mdi:face

vacuum_automation_ran_today:
  name: Indicates if vacuum automation has run today
  icon: mdi:robot-vacuum-variant

lounge_motion_sensing:
  name: Indicates if lounge motion sensing is active
  icon: mdi:robot-vacuum-variant

plant_water_notifications:
  name: Indicates if plant water notifications should be sent
  icon: mdi:water

plant_fertilize_notifications:
  name: Indicates if plant fertilize notifications should be sent
  icon: mdi:emoticon-poop
