# Initial brigtness to use for lights when they are turned on
contextual_start_brightness:
  name: Lights start brightness
  min: 0
  max: 255
  step: 1

contextual_final_brightness:
  name: Lights final brightness
  min: 0
  max: 255
  step: 1

contextual_transition_time:
  name: Lights transition time
  min: 0
  max: 120
  step: 1

contextual_color_temperature:
  name: Lights color temperature in Kelvin
  min: 2000
  max: 6500
  step: 1
