praveen_home:
  name: Indicates Praveen is home
  icon: mdi:face-profile

mar_home:
  name: Indicates Mar is home
  icon: mdi:face

vacuum_automation_ran_today:
  name: Indicates if vacuum automation has run today
  icon: mdi:robot-vacuum-variant

lounge_motion_sensing:
  name: Indicates if lounge motion sensing is active (used mostly for TV)
  icon: mdi:robot-vacuum-variant

lounge_lights_toggled_by_tv:
  name: Indicates if lounge lights were toggled by TV
  icon: mdi:lightbulb-on

plant_water_notifications:
  name: Indicates if plant water notifications should be sent
  icon: mdi:water

plant_fertilize_notifications:
  name: Indicates if plant fertilize notifications should be sent
  icon: mdi:emoticon-poop

contextual_lights:
  name: If lights should use time based color and brightness levels
  icon: mdi:lightbulb-on

motion_lighting:
  name: If lights should react to motion sensing (only living room lights off will be disabled) 
  icon: mdi:lightbulb-on
