# Grouping all the lights here

- platform: group
  name: Bedroom lights
  entities:
  - light.bedroom_light_1
  - light.bedroom_light_2
  - light.bedroom_light_3
  
- platform: group
  name: Ensuite lights
  entities:
  - light.ensuite_light_1
  - light.ensuite_light_2

- platform: group
  name: Cooktop lights
  entities:
  - light.microwave_light
  - light.cooking_lights

- platform: group
  name: Kitchen lights
  entities:
  - light.kitchen_light_1
  - light.kitchen_light_2
  - light.kitchen_light_3

- platform: group
  name: Dining lights
  entities:
  - light.dining_light_1
  - light.dining_light_2

- platform: group
  name: Lounge lights
  entities:
  - light.lounge_light_1
  - light.lounge_light_2
  - light.lounge_light_3
  - light.lounge_light_4
  - light.lounge_light_5
  - light.lounge_light_6

- platform: group
  name: Living room lights
  entities:
  - light.lounge_lights
  - light.kitchen_lights
  - light.dining_lights

- platform: group
  name: Entrance lights
  entities:
  - light.entrance_light_1
  - light.entrance_light_2
  - light.entrance_light_3

- platform: group
  name: Corridor lights
  entities:
  - light.corridor_light_1
  - light.corridor_light_2
  - light.corridor_light_3

- platform: group
  name: Hallway lights
  entities:
  - light.corridor_lights
  - light.entrance_lights

