  include:
    domains:
      - cover
      - input_boolean
      - input_select
      - light
      - media_player
      - switch
      - person
      - vacuum
      - automation
      - script
      - input_number
      - input_select
      - device_tracker
      - binary_sensor
      - timer
  exclude:
    domains:
      - sun
      - camera
      - group
      - sensor
      - weather
      - zone
