mode: yaml
resources:
- url: /hacsfiles/vacuum-card/vacuum-card.js
  type: module
- url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
  type: module
- url: /hacsfiles/button-card/button-card.js
  type: module
- url: /hacsfiles/bar-card/bar-card.js
  type: module
- url: //hacsfiles/battery-state-card/battery-state-card.js
  type: module
- url: /hacsfiles/lovelace-layout-card/layout-card.js
  type: module
- url: /hacsfiles/lovelace-card-mod/card-mod.js
  type: module
