mode: yaml
resources:
- url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
  type: module
- url: /hacsfiles/vacuum-card/vacuum-card.js
  type: module
- url: /hacsfiles/button-card/button-card.js
  type: module
- url: /hacsfiles/battery-state-card/battery-state-card.js
  type: module
- url: /hacsfiles/lovelace-layout-card/layout-card.js
  type: module
- url: /hacsfiles/lovelace-card-mod/card-mod.js
  type: module
- url: /hacsfiles/lovelace-auto-entities/auto-entities.js
  type: module
- url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js
  type: module
- url: /hacsfiles/decluttering-card/decluttering-card.js
  type: module
- url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
  type: module
- url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
  type: module
- url: /hacsfiles/flex-horseshoe-card/flex-horseshoe-card.js
  type: module
- url: /hacsfiles/bar-card/bar-card.js
  type: module
