sago_palm:
  sensors:
    moisture: sensor.miflora_sago_palm_moisture
    battery: sensor.miflora_sago_palm_battery
    temperature: sensor.miflora_sago_palm_temperature
    conductivity: sensor.miflora_sago_palm_conductivity
    brightness: sensor.miflora_sago_palm_light
  min_moisture: 15
  max_moisture: 60
  min_conductivity: 350
  max_conductivity: 2000
  min_brightness: 3500
  max_brightness: 65000
  min_temperature: 6
  max_temperature: 32

spineless_yucca:
  sensors:
    moisture: sensor.miflora_spineless_yucca_moisture
    battery: sensor.miflora_spineless_yucca_battery
    temperature: sensor.miflora_spineless_yucca_temperature
    conductivity: sensor.miflora_spineless_yucca_conductivity
    brightness: sensor.miflora_spineless_yucca_light
  min_moisture: 15
  max_moisture: 60
  min_conductivity: 350
  max_conductivity: 2000
  min_brightness: 1500
  max_brightness: 20000
  min_temperature: 8
  max_temperature: 32

rubber_plant:
  sensors:
    moisture: sensor.miflora_rubber_plant_moisture
    battery: sensor.miflora_rubber_plant_battery
    temperature: sensor.miflora_rubber_plant_temperature
    conductivity: sensor.miflora_rubber_plant_conductivity
    brightness: sensor.miflora_rubber_plant_light
  min_moisture: 15
  max_moisture: 60
  min_conductivity: 350
  max_conductivity: 2000
  min_brightness: 1000
  max_brightness: 30000
  min_temperature: 10
  max_temperature: 35

swiss_cheese:
  sensors:
    moisture: sensor.miflora_swiss_cheese_moisture
    battery: sensor.miflora_swiss_cheese_battery
    temperature: sensor.miflora_swiss_cheese_temperature
    conductivity: sensor.miflora_swiss_cheese_conductivity
    brightness: sensor.miflora_swiss_cheese_light
  min_moisture: 15
  max_moisture: 60
  min_conductivity: 350
  max_conductivity: 2000
  min_brightness: 800
  max_brightness: 15000
  min_temperature: 12
  max_temperature: 32

cat_palm:
  sensors:
    moisture: sensor.miflora_cat_palm_moisture
    battery: sensor.miflora_cat_palm_battery
    temperature: sensor.miflora_cat_palm_temperature
    conductivity: sensor.miflora_cat_palm_conductivity
    brightness: sensor.miflora_cat_palm_light
  min_moisture: 15
  max_moisture: 60
  min_conductivity: 350
  max_conductivity: 2000
  min_brightness: 800
  max_brightness: 22000
  min_temperature: 10
  max_temperature: 32

spider_plant:
  sensors:
    moisture: sensor.miflora_spider_plant_moisture
    battery: sensor.miflora_spider_plant_battery
    temperature: sensor.miflora_spider_plant_temperature
    conductivity: sensor.miflora_spider_plant_conductivity
    brightness: sensor.miflora_spider_plant_light
  min_moisture: 15
  max_moisture: 60
  min_conductivity: 200
  max_conductivity: 1300
  min_brightness: 500
  max_brightness: 30000
  min_temperature: 10
  max_temperature: 32

dumbcane:
  sensors:
    moisture: sensor.miflora_dumbcane_moisture
    battery: sensor.miflora_dumbcane_battery
    temperature: sensor.miflora_dumbcane_temperature
    conductivity: sensor.miflora_dumbcane_conductivity
    brightness: sensor.miflora_dumbcane_light
  min_moisture: 15
  max_moisture: 60
  min_conductivity: 200
  max_conductivity: 1500
  min_brightness: 1500
  max_brightness: 25000
  min_temperature: 12
  max_temperature: 32

dragon_tree:
  sensors:
    moisture: sensor.miflora_dragon_tree_moisture
    battery: sensor.miflora_dragon_tree_battery
    temperature: sensor.miflora_dragon_tree_temperature
    conductivity: sensor.miflora_dragon_tree_conductivity
    brightness: sensor.miflora_dragon_tree_light
  min_moisture: 15
  max_moisture: 60
  min_conductivity: 200
  max_conductivity: 1500
  min_brightness: 2000
  max_brightness: 50000
  min_temperature: 10
  max_temperature: 35

chilli_plant:
  sensors:
    moisture: sensor.miflora_chilli_plant_moisture
    battery: sensor.miflora_chilli_plant_battery
    temperature: sensor.miflora_chilli_plant_temperature
    conductivity: sensor.miflora_chilli_plant_conductivity
    brightness: sensor.miflora_chilli_plant_light
  min_moisture: 15
  max_moisture: 60
  min_conductivity: 150
  max_conductivity: 2000
  min_brightness: 3000
  max_brightness: 95000
  min_temperature: 10
  max_temperature: 35

cherry_tomato:
  sensors:
    moisture: sensor.miflora_cherry_tomato_moisture
    battery: sensor.miflora_cherry_tomato_battery
    temperature: sensor.miflora_cherry_tomato_temperature
    conductivity: sensor.miflora_cherry_tomato_conductivity
    brightness: sensor.miflora_cherry_tomato_light
  min_moisture: 20
  max_moisture: 65
  min_conductivity: 350
  max_conductivity: 2000
  min_brightness: 3500
  max_brightness: 130000
  min_temperature: 10
  max_temperature: 32

dining_left:
  sensors:
    moisture: sensor.miflora_dining_left_moisture
    battery: sensor.miflora_dining_left_battery
    temperature: sensor.miflora_dining_left_temperature
    conductivity: sensor.miflora_dining_left_conductivity
    brightness: sensor.miflora_dining_left_light
  min_moisture: 7
  max_moisture: 50
  min_conductivity: 100
  max_conductivity: 1000
  min_brightness: 3000
  max_brightness: 100000
  min_temperature: 5
  max_temperature: 35

dining_middle:
  sensors:
    moisture: sensor.miflora_dining_middle_moisture
    battery: sensor.miflora_dining_middle_battery
    temperature: sensor.miflora_dining_middle_temperature
    conductivity: sensor.miflora_dining_middle_conductivity
    brightness: sensor.miflora_dining_middle_light
  min_moisture: 7
  max_moisture: 50
  min_conductivity: 300
  max_conductivity: 1000
  min_brightness: 1500
  max_brightness: 35000
  min_temperature: 8
  max_temperature: 35

dining_right:
  sensors:
    moisture: sensor.miflora_dining_right_moisture
    battery: sensor.miflora_dining_right_battery
    temperature: sensor.miflora_dining_right_temperature
    conductivity: sensor.miflora_dining_right_conductivity
    brightness: sensor.miflora_dining_right_light
  min_moisture: 7
  max_moisture: 50
  min_conductivity: 300
  max_conductivity: 1000
  min_brightness: 3000
  max_brightness: 80000
  min_temperature: 5
  max_temperature: 35

money_plant:
  sensors:
    moisture: sensor.miflora_money_plant_moisture
    battery: sensor.miflora_money_plant_battery
    temperature: sensor.miflora_money_plant_temperature
    conductivity: sensor.miflora_money_plant_conductivity
    brightness: sensor.miflora_money_plant_light
  min_moisture: 15
  max_moisture: 65
  min_conductivity: 350
  max_conductivity: 2000
  min_brightness: 800
  max_brightness: 9000
  min_temperature: 10
  max_temperature: 32

debbie:
  sensors:
    moisture: sensor.miflora_debbie_moisture
    battery: sensor.miflora_debbie_battery
    temperature: sensor.miflora_debbie_temperature
    conductivity: sensor.miflora_debbie_conductivity
    brightness: sensor.miflora_debbie_light
  min_moisture: 7
  max_moisture: 50
  min_conductivity: 300
  max_conductivity: 1000
  min_brightness: 4000
  max_brightness: 90000
  min_temperature: 6
  max_temperature: 35

moonstone:
  sensors:
    moisture: sensor.miflora_moonstone_moisture
    battery: sensor.miflora_moonstone_battery
    temperature: sensor.miflora_moonstone_temperature
    conductivity: sensor.miflora_moonstone_conductivity
    brightness: sensor.miflora_moonstone_light
  min_moisture: 7
  max_moisture: 50
  min_conductivity: 300
  max_conductivity: 1000
  min_brightness: 3500
  max_brightness: 80000
  min_temperature: 5
  max_temperature: 35

pigs_ear:
  sensors:
    moisture: sensor.miflora_pigs_ear_moisture
    battery: sensor.miflora_pigs_ear_battery
    temperature: sensor.miflora_pigs_ear_temperature
    conductivity: sensor.miflora_pigs_ear_conductivity
    brightness: sensor.miflora_pigs_ear_light
  min_moisture: 7
  max_moisture: 50
  min_conductivity: 300
  max_conductivity: 1000
  min_brightness: 3000
  max_brightness: 70000
  min_temperature: 10
  max_temperature: 35

three_oclock:
  sensors:
    moisture: sensor.miflora_three_oclock_moisture
    battery: sensor.miflora_three_oclock_battery
    temperature: sensor.miflora_three_oclock_temperature
    conductivity: sensor.miflora_three_oclock_conductivity
    brightness: sensor.miflora_three_oclock_light
  min_moisture: 7
  max_moisture: 50
  min_conductivity: 300
  max_conductivity: 1000
  min_brightness: 3500
  max_brightness: 50000
  min_temperature: 5
  max_temperature: 35
