decluttering_templates: !include_dir_merge_named lovelace/templates

title: Home Control Center

views:
- !include /config/lovelace/views/view_home.yaml
- !include /config/lovelace/views/view_server_monitor.yaml
- !include /config/lovelace/views/view_covid19.yaml
