title: Home Control Center

button_card_templates: !include /config/lovelace/templates/button_card.yaml
decluttering_templates: !include /config/lovelace/templates/decluttering.yaml

views:
- !include /config/lovelace/views/view_home.yaml
- !include /config/lovelace/views/view_sensors.yaml
- !include /config/lovelace/views/view_server_monitor.yaml
- !include /config/lovelace/views/view_covid19.yaml
