#### Door based automations. There are two types.
# 1. Simple door based automations
#     Just turns lights on or off based on door state.
# 2. Door + timers based automations
#     Starts a timer and turns them off timer runs out

#============================================================
#===================          SIMPLE    =====================
#============================================================

##################    Shoe storage door    ##################
- alias: Shoe storage door opened
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.shoe_storage_door
    to: 'on'
  action:
    service: script.lights_on_smart
    data:
      entity_id: light.shoe_storage_light

- alias: Shoe storage door closed
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.shoe_storage_door
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.shoe_storage_light

##################    Electronics storage door    ##################
- alias: Electronics storage door opened
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.electronics_storage_door
    to: 'on'
  action:
    service: script.lights_on_smart
    data:
      entity_id: light.electronics_storage_light

- alias: Electronics storage door closed
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.electronics_storage_door
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.electronics_storage_light

##################    Balcony door    ##################
- alias: Balcony door opened and it's dark
  mode: queued
  trigger:
  - platform: state
    entity_id: binary_sensor.balcony_door
    to: 'on'
  - platform: numeric_state
    entity_id: sensor.dining_activity
    below: 18
    for:
      minutes: 15
  condition:
  - condition: state
    entity_id: binary_sensor.balcony_door
    state: 'on'
  - condition: numeric_state
    entity_id: sensor.dining_activity
    below: 18
  - condition: or
    conditions:
    - condition: sun
      after: sunset
      after_offset: "-01:00:00"
    - condition: sun
      before: sunrise
      before_offset: "01:00:00"
  action:
    service: script.lights_on_smart
    data:
      entity_id: light.sonoff_100094996f

- alias: Balcony door closed
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.balcony_door
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.sonoff_100094996f


#============================================================
#===================         TIMER      =====================
#============================================================

##################    Entrance door    ##################
- alias: Entrance door opened
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.entrance_door
    to: 'on'
  action:
  - service: script.lights_on_smart
    data:
      entity_id: light.entrance_lights
  - service: timer.start
    entity_id: timer.entrance_door_timer

- alias: Entrance door timer finished
  mode: queued
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.entrance_door_timer
  action:
    service: light.turn_off
    entity_id: light.entrance_lights

##################    Ensuite door    ##################
- alias: Ensuite door opened
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.ensuite_door
    to: 'on'
  condition:
  - condition: state
    entity_id: light.ensuite_lights
    state: 'off'
  action:
  - service: script.lights_on_smart
    data:
      entity_id: light.ensuite_lights
  - service: timer.start
    entity_id: timer.ensuite_door_timer

- alias: Ensuite door timer finished
  mode: queued
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.ensuite_door_timer
  action:
    service: light.turn_off
    entity_id: light.ensuite_lights
