# Mark Praveen's not home
- alias: Praveen left home zone
  trigger:
    platform: state
    entity_id: device_tracker.praveen_phone
    state: away
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.praveen_home

# Mark Praveen's home
- alias: Praveen enter home zone
  trigger:
    platform: state
    entity_id: device_tracker.praveen_phone
    state: home
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.praveen_home
