#=================================================
# Single motion sensing: Involves
# - one motion sensor
# - light level sensing
# - sun position based offsets (optional)
#=================================================

##################    Lounge    ##################
- alias: Lounge motion detected
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.lounge_activity
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.lounge_motion_sensing
    state: 'on'
  - condition: numeric_state
    entity_id: sensor.lounge_activity
    below: 18
  - condition: or
    conditions:
    - condition: sun
      after: sunset
      after_offset: "-01:00:00"
    - condition: sun
      before: sunrise
      before_offset: "01:00:00"
  action:
    service: script.lights_on_smart
    data:
      entity_id: light.lounge_lights

- alias: Lounge motion ended
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.lounge_activity
    to: 'off'
    for:
      minutes: 20
  condition:
  - condition: state
    entity_id: input_boolean.motion_lighting
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.lounge_lights

##################    Dining    ##################
- alias: Dining motion detected
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.dining_activity
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.dining_activity
    below: 18
  - condition: or
    conditions:
    - condition: sun
      after: sunset
      after_offset: "-01:00:00"
    - condition: sun
      before: sunrise
      before_offset: "01:00:00"
  action:
    service: script.lights_on_smart
    data:
      entity_id: light.dining_lights

- alias: Dining motion ended
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.dining_activity
    to: 'off'
    for:
      minutes: 20
  condition:
  - condition: state
    entity_id: input_boolean.motion_lighting
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.dining_lights

##################    Corridor    ##################
- alias: Corridor motion detected
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.corridor_activity
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.corridor_activity
    below: 18
  action:
    service: script.lights_on_smart
    data:
      entity_id: light.corridor_lights

- alias: Corridor motion ended
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.corridor_activity
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    entity_id: light.corridor_lights

##################    Entrance    ##################
- alias: Entrance motion detected
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.entrance_activity
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.entrance_activity
    below: 18
  action:
  - service: timer.cancel
    entity_id: timer.entrance_door_timer
  - service: script.lights_on_smart
    data:
      entity_id: light.entrance_lights

- alias: Entrance motion ended
  mode: queued
  trigger:
    platform: state
    entity_id: binary_sensor.entrance_activity
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    entity_id: light.entrance_lights

#=================================================
# Dual motion sensing:
# Involves only two motion sensors and 
# lighting level sensing from one sensor
#=================================================

##################   Kitchen & Living room   ##################
- alias: Kitchen or Living room motion detected
  mode: queued
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_entrance_activity
    to: 'on'
  - platform: state
    entity_id: binary_sensor.kitchen_activity
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.kitchen_activity
    below: 18
  - condition: or
    conditions:
    - condition: sun
      after: sunset
      after_offset: "-01:00:00"
    - condition: sun
      before: sunrise
      before_offset: "01:00:00"
  action:
    service: script.lights_on_smart
    data:
      entity_id: light.kitchen_lights

- alias: Kitchen and Living room motion ended
  mode: queued
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_entrance_activity
    to: 'off'
    for:
      minutes: 20
  - platform: state
    entity_id: binary_sensor.kitchen_activity
    to: 'off'
    for:
      minutes: 20
  condition:
  - condition: state
    entity_id: binary_sensor.living_room_entrance_activity
    state: 'off'
  - condition: state
    entity_id: binary_sensor.kitchen_activity
    state: 'off'
  - condition: state
    entity_id: input_boolean.motion_lighting
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.kitchen_lights


##################   Ensuite - toiler + shower   ##################
- alias: Ensuite motion detected
  mode: queued
  trigger:
  - platform: state
    entity_id: binary_sensor.ensuite_shower_activity
    to: 'on'
  - platform: state
    entity_id: binary_sensor.ensuite_toilet_activity
    to: 'on'
  action:
  - service: timer.cancel
    entity_id: timer.ensuite_door_timer
  - service: script.lights_on_smart
    data:
      entity_id: light.ensuite_lights

- alias: Ensuite motion ended
  mode: queued
  trigger:
  - platform: state
    entity_id: binary_sensor.ensuite_shower_activity
    to: 'off'
    for:
      minutes: 10
  - platform: state
    entity_id: binary_sensor.ensuite_toilet_activity
    to: 'off'
    for:
      minutes: 10
  condition:
  - condition: state
    entity_id: binary_sensor.ensuite_shower_activity
    state: 'off'
  - condition: state
    entity_id: binary_sensor.ensuite_toilet_activity
    state: 'off'
  action:
    service: light.turn_off
    entity_id: light.ensuite_lights
