- alias: Living room switch 1 - ON press - disable motion lighting
  mode: parallel
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: living_room_switch_1
      event: 1000 # press on button
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.motion_lighting

- alias: Living room switch 1 - OFF press - enable motion lighting
  mode: parallel
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: living_room_switch_1
      event: 4000 # press the off button
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.motion_lighting
