- alias: Update plant problems
  trigger:
    platform: time_pattern
    minutes: "/5" # Every 5 mins
  action:
    service: python_script.plant_problems

- alias: Clear plant problem notifications
  trigger:
    platform: time
    at: 
    - "01:00:00" # At 1:00 AM
  action:
    service: python_script.clear_plant_notifications

- alias: Notify about plant problems
  trigger:
    platform: time
    at: 
    - "06:00:00" # At 6:00 AM
  action:
    service: python_script.notify_plant_problems
