- alias: Update plant problems
  trigger:
    platform: time_pattern
    minutes: "/5" # Every 5 mins
  action:
    service: python_script.plant_problems

- alias: Notify about plant problems
  trigger:
    platform: time
    at: 
    - "05:00:00" # At 5:00 AM
    - "17:00:00" # At 5:00 PM
  action:
    service: python_script.notify_plant_problems
