#### Voice command automation ####
- alias: Clean room with IFTTT
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: vacuum_clean_room_voice_command
  action:
    service: python_script.vacuum_clean_room
    data_template:
      room_phrase: "{{ trigger.event.data.room }}"

#### Scheduled cleaning - Monday, Wednesday, Friday ####
- alias: Vacuum schedule for Monday / Wednesday / Friday
  trigger:
  - platform: state
    entity_id: input_boolean.praveen_home
    to: 'off'
  - platform: state
    entity_id: input_boolean.mar_home
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.praveen_home
    state: 'off'
  - condition: state
    entity_id: input_boolean.mar_home
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacuum_automation_ran_today
    state: 'off'
  - condition: time
    after: '07:00:00'
    before: '22:30:00'
    weekday:
    - mon
    - wed
    - fri
  action:
  - service: python_script.vacuum_clean_room
    data_template:
      room_phrase: "kitchen and dining"
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.vacuum_automation_ran_today

#### Scheduled cleaning - Tuesday, Thursday, Saturday ####
- alias: Vacuum schedule for Tueday / Thursday / Saturday
  trigger:
  - platform: state
    entity_id: input_boolean.praveen_home
    to: 'off'
  - platform: state
    entity_id: input_boolean.mar_home
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.praveen_home
    state: 'off'
  - condition: state
    entity_id: input_boolean.mar_home
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacuum_automation_ran_today
    state: 'off'
  - condition: time
    after: '07:00:00'
    before: '22:30:00'
    weekday:
    - tue
    - thu
    - sat
  action:
  - service: python_script.vacuum_clean_room
    data_template:
      room_phrase: "lounge, kitchen and dining"
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.vacuum_automation_ran_today

#### Scheduled cleaning - Sunday ####
- alias: Vacuum schedule for Sunday
  trigger:
  - platform: state
    entity_id: input_boolean.praveen_home
    to: 'off'
  - platform: state
    entity_id: input_boolean.mar_home
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.praveen_home
    state: 'off'
  - condition: state
    entity_id: input_boolean.mar_home
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacuum_automation_ran_today
    state: 'off'
  - condition: time
    after: '07:00:00'
    before: '22:30:00'
    weekday:
    - sun
  action:
  - service: python_script.vacuum_clean_room
    data_template:
      room_phrase: "lounge, kitchen, dining and hallway"
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.vacuum_automation_ran_today

#### Reset vacuum ran status for the day #####
- alias: Reset vacuum ran status
  trigger:
    platform: time
    at: "00:30:00"
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.vacuum_automation_ran_today
