# services.yaml
update_contextual_params:
  description: Sets the contextual parameters used for lights based on time of the day
  fields:
    hour:
      description: Current time's hour value
      example: "23"
    minute:
      description: Current time's minute value
      example: "30"

vacuum_clean_room:
  description: Sends robovac to clean specified rooms
  fields:
    room_phrase:
      description: A text phrase of the room / rooms to clean
      example: "Kitchen and Dining"

plant_problems:
  description: Updates the list of plants that need attention

notify_plant_problems:
  description: Sends notifications for each plant that need attention
