name: HA config validation

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Prepare environment
      run: |
        cp config/secrets.yaml.sample config/secrets.yaml
        touch config/adbkey

    - name: Start Home Assistant
      run: |
        docker run -d --name="home-assistant" \
        -v /config:/config \
        -v /etc/localtime:/etc/localtime:ro \
        --net=host \
        homeassistant/home-assistant:stable
    
    - name: Verify config
      run: |
        docker exec home-assistant \
          python -m homeassistant --script check_config --config /config --info all
